name: FlutterPokedex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.7.0"
  firebase_analytics: "^7.0.1"
  firebase_crashlytics: "^0.4.0+1"
  cupertino_icons: ^1.0.0
  json_annotation: ^3.1.1
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  bloc_pattern: ^2.5.1
  rxdart: ^0.24.0
  google_fonts: ^1.1.0
  shimmer: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
